#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : template-glib
Version  : 3.32.0
Release  : 1
URL      : https://gitlab.gnome.org/GNOME/template-glib/-/archive/3.32.0/template-glib-3.32.0.tar.gz
Source0  : https://gitlab.gnome.org/GNOME/template-glib/-/archive/3.32.0/template-glib-3.32.0.tar.gz
Summary  : A templating library for GLib
Group    : Development/Tools
License  : LGPL-2.1
Requires: template-glib-data = %{version}-%{release}
Requires: template-glib-lib = %{version}-%{release}
Requires: template-glib-license = %{version}-%{release}
Requires: template-glib-locales = %{version}-%{release}
BuildRequires : bison
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : flex

%description
# Template-GLib
Template-GLib is a library to help you generate text based on a template and
user defined state. Template-GLib does not use a language runtime, so it is
safe to use from any GObject-Introspectable language.

%package data
Summary: data components for the template-glib package.
Group: Data

%description data
data components for the template-glib package.


%package dev
Summary: dev components for the template-glib package.
Group: Development
Requires: template-glib-lib = %{version}-%{release}
Requires: template-glib-data = %{version}-%{release}
Provides: template-glib-devel = %{version}-%{release}
Requires: template-glib = %{version}-%{release}

%description dev
dev components for the template-glib package.


%package lib
Summary: lib components for the template-glib package.
Group: Libraries
Requires: template-glib-data = %{version}-%{release}
Requires: template-glib-license = %{version}-%{release}

%description lib
lib components for the template-glib package.


%package license
Summary: license components for the template-glib package.
Group: Default

%description license
license components for the template-glib package.


%package locales
Summary: locales components for the template-glib package.
Group: Default

%description locales
locales components for the template-glib package.


%prep
%setup -q -n template-glib-3.32.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1552660419
export LDFLAGS="${LDFLAGS} -fno-lto"
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/template-glib
cp COPYING %{buildroot}/usr/share/package-licenses/template-glib/COPYING
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang template-glib

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Template-1.0.typelib
/usr/share/gir-1.0/*.gir
/usr/share/vala/vapi/template-glib-1.0.deps
/usr/share/vala/vapi/template-glib-1.0.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/template-glib-1.0/tmpl-debug.h
/usr/include/template-glib-1.0/tmpl-enums.h
/usr/include/template-glib-1.0/tmpl-error.h
/usr/include/template-glib-1.0/tmpl-expr-types.h
/usr/include/template-glib-1.0/tmpl-expr.h
/usr/include/template-glib-1.0/tmpl-glib.h
/usr/include/template-glib-1.0/tmpl-scope.h
/usr/include/template-glib-1.0/tmpl-symbol.h
/usr/include/template-glib-1.0/tmpl-template-locator.h
/usr/include/template-glib-1.0/tmpl-template.h
/usr/include/template-glib-1.0/tmpl-version-macros.h
/usr/include/template-glib-1.0/tmpl-version.h
/usr/lib64/libtemplate_glib-1.0.so
/usr/lib64/pkgconfig/template-glib-1.0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libtemplate_glib-1.0.so.0
/usr/lib64/libtemplate_glib-1.0.so.0.3200.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/template-glib/COPYING

%files locales -f template-glib.lang
%defattr(-,root,root,-)

